### ISSUE TITLE
Main Python for the next VM will be Python 3

### ISSUE THREAD

**Issue by daniviga** [gem/oq-installers#90]
The main python for the next release of the OpenQuake VM will be Python 3.

This breaks compatibility with some toolkits:
- [x] RMTK -> use py2-venv
- [x] gmpe-smtk (Port to Python 3 is WIP by @g-weatherill )
- [x] catalogue_toolkit -> use py2-venv
- [x] CatalogueTool-Lite -> use py2-venv
- [x] hazard-notebooks

We have to:

- [x] Decide which toolkits are obsolete/unused and remove them
- [x] Eventually add new toolkits or port the existing ones
- [x] Provide a secondary python2 venv for the uncompatible toolkits we want to keep. These must not depend on the Engine[1].

[1] plan B will be installing a copy of an old engine to be used as library

Part of: https://github.com/gem/oq-engine/issues/2803
cc @mmpagani @klunk386 @raoanirudh

**Comment by g-weatherill** [comment]
As you indicate, the migration of the gmpe-smtk to Python 3 is underway. Most of the code is working but I have some tests failing for unrelated issues. I'm [hopefully] on schedule to have this migrated in time for oq-engine 3.0.

As far as I recall, the catalogue_toolkit has no OpenQuake dependencies (but I'll check). Migration to Python 3 could take a while because of strings/bytes incompatibilities so I would favour maintaining a venv on the VMs with Python 2 (incl. numpy, scipy, matplotlib, basemap [which will be deprecated soon anyway], pandas)

Most of the notebooks are out of date anyway, so I'm not sure they should be maintained. Are they still used in trainings? I use different ones now for teaching.

**Comment by raoanirudh** [comment]
The rmtk needs to be migrated to Python 3 and this may not happen anytime soon.

@daniviga, the rmtk does not depend on the engine, so the proposed Python2 venv option should work for now.

@g-weatherill have you tried working with [JupyterLab](https://blog.jupyter.org/jupyterlab-is-ready-for-users-5a6f039b8906) yet? Seems quite promising!

**Comment by g-weatherill** [comment]
Thanks @raoanirudh I'll take a look at JupyterLab.

Just checked and the catalogue_toolkit has no OQ dependencies - so it can be run in a Python 2 venv without OQ.

**Comment by daniviga** [comment]
Thanks @g-weatherill @raoanirudh, good news, I've updated the description

**Comment by daniviga** [comment]
Engine 3.0 released, closing.
